---
- name: Configure VMWare kernel modules
  modprobe:
    name: "{{ item }}"
    state: present
  with_items:
    - vmw_vmci
    - vmmon

- name: Configure VMWare services
  systemd:
    name: "{{ item }}"
    enabled: yes
    state: started
  with_items:
    - vmware-networks.service
    - vmware-usbarbitrator.service
    - vmware-hostd.service
