---
# vars file for roles/gui-base
xorg_packages:
  - xorg
  - xorg-xrdb
  - compton
  - xf86-video-intel
  - i3-gaps
  - i3status
  - i3blocks
  #- i3lock 
  - i3lock-fancy-git # variant that does blurring and font customization
  - xclip
  - xsel
  - feh
  - imagemagick # used by feh to support SVG
  - arandr
  - scrot

wayland_packages:
  - wayland
  - xorg-server-xwayland
  - sway

gui_packages:
  - gdm
  - firefox
  - google-chrome
  - terminator
  - alacritty-git
  - w3m
  - dmenu
  - rofi
  #- spotify-stable # TODO: re-enable if the authors ever fix the PGP key error in the package
  - playerctl
  - pavucontrol
  - network-manager-applet
  - networkmanager-dmenu-git
  - blueberry
  - qemu
  - virt-manager
  - dunst
  - xss-lock
  - lxappearance
  - redshift

theme_packages:
  - arc-gtk-theme
  - adapta-gtk-theme
  - gnome-icon-theme
  - gnome-icon-theme-extras
  - moka-icon-theme
  - arc-icon-theme

wine_packages:
  - wine
  - wine_gecko
  - wine-mono
  - lib32-mesa
  - mesa
  - lib32-libpulse
  - libpulse
  - lib32-openal
  - openal
  - lib32-libxml2
  - libxml2
  - lib32-mpg123
  - mpg123
  - lib32-lcms2
  - lcms2
  - lib32-giflib
  - giflib
  - lib32-libpng
  - libpng
  - lib32-gnutls
  - gnutls
  - lib32-libcups
  - libcups
  - winetricks
  - lib32-libxrandr
  - lib32-libxinerama
  - samba
  - pygtk #technically this is a CrossOver dependency

