---
# vars file for roles/gui-base
xorg_packages:
  - xorg
  - xorg-xrdb
  - compton
  - xf86-video-intel
  - i3-wm
  - i3lock
  - i3status
  - i3blocks
  - xclip
  - xsel

wayland_packages:
  - wayland
  - xorg-server-xwayland
  - sway

gui_packages:
  - gdm
  - firefox
  - google-chrome
  - terminator
  - dmenu
  - rofi
  #- spotify-stable # TODO: re-enable if the authors ever fix the PGP key error in the package
  - network-manager-applet
  - networkmanager-dmenu-git
  - blueberry
  - qemu
  - virt-manager

wine_packages:
  - wine
  - wine_gecko
  - wine-mono
  - lib32-mesa
  - mesa
  - lib32-libpulse
  - libpulse
  - lib32-openal
  - openal
  - lib32-libxml2
  - libxml2
  - lib32-mpg123
  - mpg123
  - lib32-lcms2
  - lcms2
  - lib32-giflib
  - giflib
  - lib32-libpng
  - libpng
  - lib32-gnutls
  - gnutls
  - lib32-libcups
  - libcups
  - winetricks
  - lib32-libxrandr
  - lib32-libxinerama
  - samba
  - pygtk #technically this is a CrossOver dependency

