---
# vars file for roles/gui-base
xorg_packages:
  - xorg
  - xorg-xrdb
  - compton
  - xf86-video-intel
  - i3

wayland_packages:
  - wayland
  - xorg-server-xwayland
  - sway

gui_packages:
  - gdm
  - firefox
  - google-chrome
  - terminator
  - rofi
  #- spotify-stable # TODO: re-enable if the authors ever fix the PGP key error in the package
  - nm-dmenu
  - blueberry
