session_name: linux-devbox
start_directory: ./
windows:
  - window_name: editor
    focus: true
    panes:
    - shell_command:
        - vim
      focus: true
  - window_name: ansible
    shell_command_before: cd playbooks
    panes:
    - pane
  - window_name: shell
    panes:
    - pane
