---
# tasks file for roles/laptop-base
- name: install laptop-specific packages
  dnf:
    name: "{{ lookup('flattened', item) }}"
    state: present
  become: yes
  with_items:
      - "{{ laptop_packages }}"

