---
# tasks file for roles/laptop-base
- name: install laptop-specific packages
  aur:
    name: "{{ item }}"
    use: yay
    skip_installed: yes
  become: yes
  become_user: "{{ aur_builder_user }}"
  with_items:
      - "{{ laptop_packages }}"

