---
# tasks file for roles/xps
- name: Add intel graphics modules to initramfs
  lineinfile:
    dest: /etc/mkinitcpio.conf
    line: 'MODULES=(intel_agp i915 \1'
    regexp: '^MODULES=\((?:intel_agp i915 )?(.*)$'
    backrefs: yes
    state: present
  notify: Rebuild initramfs

# The 'keyboard' hook needs to come before the 'autodetect' hook
# otherwise external keyboards and the thunderbolt dock may not
# work when entering the boot password
# 
# This according to the arch wiki
- name: Ensure keyboard hook is not subject to autodetect
  lineinfile:
    # if the regex doesn't match, then nothing is changed.  so write a regex
    # that will match only if 'keyboard' is after 'autodetect' because it should be before
    dest: /etc/mkinitcpio.conf
    line: 'HOOKS=\1keyboard autodetect \2\3'
    regexp: '^HOOKS=(.*)autodetect (.*)keyboard (.*)$'
    backrefs: yes
    state: present
  notify: Rebuild initramfs

# Dell makes firmware updates available via the fwupd tool
# so it's handy to have that installed
- aur: name=fwupd skip_installed=yes

# Configure systemd to use hybrid-sleep
- file: path=/etc/systemd/logind.conf.d state=directory

- name: Configure sleep and hibernation
  copy:
    src: files/handle-power-events.conf
    dest: /etc/systemd/logind.conf.d/handle-power-events.conf

- name: Configure xorg power management for the screen
  copy:
    src: files/xorg-power-config.conf
    dest: /etc/X11/xorg.conf.d/10-monitor.conf

- name: Configure libinput to use sane defaults for the touch pad
  copy:
    src: files/xorg-touchpad.conf
    dest: /etc/X11/xorg.conf.d/30-touchpad.conf

- name: Set system wide env vars for HiDPI support in GUI toolkits
  copy:
    src: files/gtk-hidpi-env-vars.sh
    dest: /etc/profile.d/gtk-hidpi-env-vars.sh

- name: Install XPS packages
  aur:
    name: "{{ item }}"
    skip_installed: yes
  with_items:
    - "i7z"

