---
# tasks file for roles/xps
- name: Add intel graphics modules to initramfs
  lineinfile:
    dest: /etc/mkinitcpio.conf
    line: 'MODULES=(intel_agp i915 \1'
    regexp: '^MODULES=((?:intel_agp i915 )?(.*)$'
    backrefs: yes
    state: present
  register: modules_added

- name: Rebuild initramfs
  shell: "mkinitcpio -p linux"
  when: "modules_added|changed"
