---
# tasks file for roles/xps
- name: Add intel graphics modules to initramfs
  lineinfile:
    dest: /etc/mkinitcpio.conf
    line: 'MODULES=(nvme i915 intel_agp \1'
    regexp: '^MODULES=\((?:nvme i915 intel_agp)? (.*)$'
    backrefs: yes
    state: present
  notify: Rebuild initramfs

# The 'keyboard' hook needs to come before the 'autodetect' hook
# otherwise external keyboards and the thunderbolt dock may not
# work when entering the boot password
# 
# This according to the arch wiki
- name: Ensure keyboard hook is not subject to autodetect
  lineinfile:
    # if the regex doesn't match, then nothing is changed.  so write a regex
    # that will match only if 'keyboard' is after 'autodetect' because it should be before
    dest: /etc/mkinitcpio.conf
    line: 'HOOKS=\1keyboard autodetect \2\3'
    regexp: '^HOOKS=(.*)autodetect (.*)keyboard (.*)$'
    backrefs: yes
    state: present
  notify: Rebuild initramfs

# Dell makes firmware updates available via the fwupd tool
# so it's handy to have that installed
- aur: name=fwupd skip_installed=yes

# Perform one-time copy of fwupdate stuff into ESP
# See details at https://wiki.archlinux.org/index.php/Fwupd#Setup_for_UEFI_BIOS_upgrade
# Sadly as of this writing ansible copy of remote-to-remote doesn't support recursion
# Seems like a painfully glaring ommission to me
- name: copy fwupdate firmware files to ESP
  command: cp --recursive --update /usr/lib/fwupdate/EFI /boot

- name: configure fwupd so it will work properly when the ESP is mounted somewhere it doesn't expect
  lineinfile:
    dest: /etc/fwupd/uefi.conf
    regexp: '#OverrideESPMountPoint='
    line: 'OverrideESPMountPoint=/boot'

# Configure systemd to use hybrid-sleep
- file: path=/etc/systemd/logind.conf.d state=directory

- name: Configure sleep and hibernation
  copy:
    src: files/handle-power-events.conf
    dest: /etc/systemd/logind.conf.d/handle-power-events.conf

- name: Configure xorg power management for the screen
  copy:
    src: files/xorg-power-config.conf
    dest: /etc/X11/xorg.conf.d/10-monitor.conf

- name: Configure libinput to use sane defaults for the touch pad
  copy:
    src: files/xorg-touchpad.conf
    dest: /etc/X11/xorg.conf.d/30-touchpad.conf

- name: Set system wide env vars for HiDPI support in GUI toolkits
  copy:
    src: files/gtk-hidpi-env-vars.sh
    dest: /etc/profile.d/gtk-hidpi-env-vars.sh

- name: Install XPS packages
  aur:
    name: "{{ item }}"
    use: yaourt
    skip_installed: yes
  become: yes
  become_user: "{{ aur_builder_user }}"
  with_items:
    - "i7z"      # i7 CPU counters (probably not that useful after all)
    - "i8kutils" # fan speed control
    - libva-intel-driver # video playback acceleration for Intel integrated GPUs

  # as of this writing, the new 9370 and 9560 aren't explicitly supported
  # tell this module to ignore that
  #
  # This and other tidbits of insight into fan control on XPS systems, including
  # using i8utils to take over control of the fans from the BIOS,
  # see https://daenney.github.io/2017/11/11/arch-linux-xps-13-9360.html
- name: Fix the modprobe.d config
  lineinfile:
    path: /etc/modprobe.d/dell-smm-hwmon.conf
    regexp: ^options dell-smm-hwmon
    line: options dell-smm-hwmon restricted=0 ignore_dmi=1

