---
# tasks file for roles/xps
- name: Install XPS packages
  dnf:
    name: "{{ lookup('flattened', item) }}"
    state: present
  become: yes
  with_items:
    - "i8kutils" # fan speed control
    - libva-intel-driver # video playback acceleration for Intel integrated GPUs

