---
# tasks file for roles/xps
- name: Add intel graphics modules to initramfs
  lineinfile:
    dest: /etc/mkinitcpio.conf
    line: 'MODULES=(intel_agp i915 \1'
    regexp: '^MODULES=\((?:intel_agp i915 )?(.*)$'
    backrefs: yes
    state: present
  notify: Rebuild initramfs

# The 'keyboard' hook needs to come before the 'autodetect' hook
# otherwise external keyboards and the thunderbolt dock may not
# work when entering the boot password
# 
# This according to the arch wiki
- name: Ensure keyboard hook is not subject to autodetect
  lineinfile:
    # if the regex doesn't match, then nothing is changed.  so write a regex
    # that will match only if 'keyboard' is after 'autodetect' because it should be before
    dest: /etc/mkinitcpio.conf
    line: 'HOOKS=\1keyboard autodetect \2\3'
    regexp: '^HOOKS=(.*)autodetect (.*)keyboard (.*)$'
    backrefs: yes
    state: present
  notify: Rebuild initramfs

# Dell makes firmware updates available via the fwupd tool
# so it's handy to have that installed
- aur: name=fwupd skip_installed=yes
