---
# Tweak the fontconfig settings so they're at least somewhat pretty
- name: Enable lcdfilter
  file:
    src: /etc/fonts/conf.avail/11-lcdfilter-default.conf 
    dest: /etc/fonts/conf.d/11-lcdfilter-default.conf 
    state: link

- name: Enable subpixel rendering
  file:
    src: /etc/fonts/conf.avail/10-sub-pixel-rgb.conf
    dest: /etc/fonts/conf.d/10-sub-pixel-rgb.conf
    state: link
- name: Set sensble local fontconfig settings
  copy:
    src: fontconfig-local.conf
    dest: /etc/fonts/local.conf
