---
# Make sure the user running ansible (which we assume is the user who will be configured)
# is able to access USB devices
- name: add the current user to the vboxusers group
  user:
    name: "{{ lookup('env', 'USER') }}"
    groups:
      - vboxusers
    append: yes
  when: lookup('env', 'USER') != 'root'
