---
# tasks file for roles/gui-base
- name: Enable alacritty Copr repo
  # Info came from this: https://copr.fedorainfracloud.org/coprs/pschyska/alacritty/repo/fedora-31/pschyska-alacritty-fedora-31.repo
  yum_repository:
    name: alacritty
    description: Copr repo for alacritty owned by pschyska
    baseurl: https://copr-be.cloud.fedoraproject.org/results/pschyska/alacritty/fedora-$releasever-$basearch/
    skip_if_unavailable: yes
    gpgkey: https://copr-be.cloud.fedoraproject.org/results/pschyska/alacritty/pubkey.gpg
    repo_gpgcheck: no
    enabled: yes

- name: install alacritty from a custom repo
  dnf:
    name: alacritty
    enablerepo: alacritty
    state: present
- name: install base system packages that require X or Wayland
  dnf:
    name: "{{ lookup('flattened', item) }}"
    state: present
  become: yes
  loop:
      - "{{ wayland_packages }}"
      - "{{ gui_packages }}"
      - "{{ theme_packages }}"
      - "{{ wine_packages }}"

- import_tasks: configure-gdm.yml
- import_tasks: configure-wine.yml
#Disabling this; I hope Fedora has a sensible default already.  If not, then revisit
#- import_tasks: configure-fontconfig.yml

- name: Enable the default flathub flatpak repo
  flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    method: system

- name: install flatpak packages
  flatpak:
    name: "{{ item }}"
  loop: "{{ flatpak_packages }}"

- name: Install dropbox RPM
  dnf:
    name: "{{ dropbox_rpm_url }}"
    state: present
