---
# vars file for roles/headless-base
packages_with_annoying_pgp_problem:
    - ncurses5-compat-libs

utility_packages:
    - btrfs-progs
    - dosfstools
    - gnupg
    - the_silver_searcher
    - ripgrep # supposedly even faster than ag
    - fzf # file finder
    - fd # like ripgrep but only for listing files not searching their contents
    - tmux
    - tmuxp
    - mosh-git # until this PR in master gets released must use the master branch: https://github.com/mobile-shell/mosh/pull/939
    - [ zsh, zsh-syntax-highlighting, antigen-git ]
    - bash-completion
    - networkmanager
    - wget
    - curl
    - p7zip
    - unzip
    - unrar
    - pass
    - bluez
    - bluez-utils
    - pulseaudio
    - pulseaudio-bluetooth
    - pamixer
    - elinks
    - libnotify
    - [ gtop, htop, nmon ]
    - snapd
    - openssh
    - [ libu2f-host, yubikey-personalization, libusb, pcsclite, acsccid, ccid ] # related to working with yubikeys
    - jq
    - fio
    - bc
    - ldns # provides the dig successor drill
    - bind-tools # provides dig and nslookup
    - gnome-keyring # despite the name, not a GUI app; ensures the keyring is available even headless
    - [ bcc, bcc-tools, python-bcc, python2-bcc ] #BCC eBPF profiling tools

dev_packages:
    - neovim
    - python-neovim
    - python2-neovim
    - ranger
    - base-devel
    - git
    - git-lfs
    - python
    - python-pip
    - python-setuptools
    - python2
    - python2-pip
    - python2-setuptools
    - jdk8-openjdk
    - jdk9
    - flatbuffers
    - go
    - mono
      # dependencies for youcompleteme viM plugin
    - [ boost, boost-libs, clang, mono, ncurses5-compat-libs, nodejs, rust, cargo, cmake, make, go, npm ]
    - docker
    - swig
    - intel-opencl-runtime
    - exa  #ls-like tool but better
    - bat  #syntax and git-aware cat replacement
    - gdb

pentest_packages:
    - aircrack-ng
    - wireshark-gtk
    - nmap

console_font_packages:
    - terminus-font
    - adobe-source-code-pro-fonts
    - adobe-source-sans-pro-fonts
    - system-san-francisco-font-git
    - ttf-font-awesome-4
    - powerline-fonts
    - noto-fonts
    - nerd-fonts-complete # installs a wide range of patched fonts

