---
# vars file for roles/headless-base
packages_with_annoying_pgp_problem:
    - ncurses5-compat-libs

utility_packages:
    - btrfs-progs
    - dosfstools
    - gnupg
    - the_silver_searcher
    - ripgrep # supposedly even faster than ag
    - fzf # file finder
    - fd # like ripgrep but only for listing files not searching their contents
    - tmux
    - tmuxp
    - [ zsh, zsh-syntax-highlighting, antigen-git ]
    - bash-completion
    - networkmanager
    - wget
    - curl
    - p7zip
    - unzip
    - unrar
    - pass
    - bluez
    - bluez-utils
    - pulseaudio
    - pulseaudio-bluetooth
    - pamixer
    - elinks
    - libnotify
    - gtop
    - snapd
    - openssh
    - [ libu2f-host, yubikey-personalization, libusb, pcsclite ] # related to working with yubikeys
    - jq
    - fio
    - bc

dev_packages:
    - neovim
    - python-neovim
    - python2-neovim
    - ranger
    - base-devel
    - git
    - git-lfs
    - python
    - python-pip
    - python-setuptools
    - python2
    - python2-pip
    - python2-setuptools
    - jdk8-openjdk
    - jdk9-openjdk
    - scala
    - sbt
    - ruby
    - flatbuffers
    - go
    - mono
      # dependencies for youcompleteme viM plugin
    - [ boost, boost-libs, clang, mono, ncurses5-compat-libs, nodejs, rust, cargo, cmake, make, go, npm ]
    - docker
    - swig
    - intel-opencl-runtime

pentest_packages:
    - aircrack-ng
    - wireshark-gtk
    - nmap

# packages that apply specifically to laptops
laptop_packages:
    - wpa_supplicant
    - acpi
    - powertop
    - ethtool #for disable WoL
    - smartmontools
    - x86_energy_perf_policy # tlp uses this
    - tlp
    - systemd-boot-pacman-hook # make sure the systemd-boot binaries on /boot are in sync with the latest systemd
    - lm_sensors
    - cpupower # monitor and tweak CPU speed settings
    - thermald # monitor CPU temperature
    - mons # shell script for dealing with multiple monitors

console_font_packages:
    - terminus-font
    - adobe-source-code-pro-fonts
    - system-san-francisco-font-git
    - ttf-font-awesome-4
    - powerline-fonts
