---
# vars file for roles/headless-base
utility_packages:
    - btrfs-progs
    - gnupg
    - ag # SilverSearcher
    - ripgrep # supposedly even faster than ag
    - fzw # file finder
    - tmux
    - tmuxp
    - zsh
    - bash-completion
    - networkmanager

dev_packages:
    - neovim
    - base-devel
    - git

# packages that apply specifically to laptops
laptop_packages:
    - wpa_supplicant
    - powertop
    - ethtool #for disable WoL
    - tlp
