---
# vars file for roles/headless-base
utility_packages:
    - btrfs-progs
    - gnupg
    - the_silver_searcher
    - ripgrep # supposedly even faster than ag
    - fzf # file finder
    - tmux
    - tmuxp
    - zsh
    - bash-completion
    - networkmanager

dev_packages:
    - neovim
    - base-devel
    - git
    - python
    - python-pip
    - python-setuptools
    - python2
    - python2-pip
    - python2-setuptools

# packages that apply specifically to laptops
laptop_packages:
    - wpa_supplicant
    - powertop
    - ethtool #for disable WoL
    - tlp

# packages that should be installed via pip instead of arch
# note that pip packages are installed for the user only to avoid
# conflicts with the system packages.
pip_packages:
    pip2:
    pip3:
        - tmuxp
