---
# tasks file for roles/user-packages
- name: Installing user-level pip packages for Python 2
  pip:
    executable: pip2
    extra_args: --user
    name: "{{ pip2_packages }}"

- name: Installing user-level pip packages for Python 3
  pip:
    executable: pip3
    extra_args: --user
    name: "{{ pip3_packages }}"

- name: Install Rust tools for the current user
  shell: |
    source "{{ lookup('env', 'HOME') }}/.cargo/env"
    cargo install --force {{ item.name }}
  args:
    creates: "{{ ansible_env.HOME }}/.cargo/bin/{{ item.executable }}"
  with_items: "{{ rust_packages }}"

- name: Check out NerdFonts repo
  git:
    repo: 'https://github.com/ryanoasis/nerd-fonts.git'
    dest: "{{ ansible_env.HOME }}/.nerdfonts"
    version: "v2.0.0"
  register: nerdfonts_checkout

- name: Install NerdFonts
  shell: |
    {{ ansible_env.HOME }}/.nerdfonts/install.sh
  when: "nerdfonts_checkout.changed"
