---
# tasks file for roles/user-packages
- name: Installing user-level pip packages for Python
  pip:
    executable: pip
    extra_args: --user
    name: "{{ pip_packages }}"

- name: Install Rust tools for the current user
  shell: |
    source "{{ lookup('env', 'HOME') }}/.cargo/env"
    cargo install --force {{ item.name }}
  args:
    creates: "{{ ansible_env.HOME }}/.cargo/bin/{{ item.executable }}"
  with_items: "{{ rust_packages }}"

- name: Check out NerdFonts repo
  git:
    repo: 'https://github.com/ryanoasis/nerd-fonts.git'
    dest: "{{ ansible_env.HOME }}/.nerdfonts"
    version: "v2.0.0"
  register: nerdfonts_checkout

- name: Install NerdFonts
  shell: |
    {{ ansible_env.HOME }}/.nerdfonts/install.sh
  when: "nerdfonts_checkout.changed"

- name: Install terraform
  shell: |
    cd /tmp
    curl --silent https://releases.hashicorp.com/terraform/0.12.23/terraform_{{ terraform_version }}_linux_amd64.zip  -o terraform.zip
    unzip terraform.zip
    cp terraform {{ ansible_env.HOME}}/.local/bin
  args:
    creates: "{{ansible_env.HOME}}/.local/bin/terraform"
