---
# Configure a simple firewall that blocks everything except SSH
- name: Install `ufw` package
  package:
    name: ufw
    state: present

- name: Enable ufw with a default `deny` rule
  ufw:
    state: enabled
    policy: deny
    logging: on

- name: Enable SSH but with rate limiting
  ufw:
    rule: limit
    port: ssh
    proto: tcp

