---
# Configure the blackarch repo for pentesting tools
- name: Check if there is already a blackarch repo
  command: grep -q "\[blackarch\]" /etc/pacman.conf
  register: has_blackarch
  ignore_errors: true

- name: Clear the packman gpg config and let the bootstrap script recreate it
  file:
    path: /etc/pacman.d/gnupg
    state: absent
  when: has_blackarch is failed

- name: Download blackarch setup script
  get_url:
    url: https://blackarch.org/strap.sh
    checksum: sha1:6f152b79419491db92c1fdde3fad2d445f09aae3
    dest: /tmp/strap.sh
    mode: u+rx
  when: has_blackarch is failed

- name: Modify blackarch setup script so it reads from stdin instead of a TTY
  replace:
    path: /tmp/strap.sh
    regexp: '\< \/dev\/tty'
    replace: ''
  when: has_blackarch is failed

  # Note the ugly hack, feeding input to the script.  First newline is to accept default mirror, second
  # is to answer 'n' to the prompt to perform a system update
- name: Run blackarch script
  command: printf "\nn\n" | /tmp/strap.sh
  when: has_blackarch is failed


