---
- name: start tlp and thermald services
  systemd:
    state: started
    enabled: True
    name: "{{ item }}"
  with_items:
    - tlp.service
    - tlp-sleep.service
    - thermald.service

- name: mask rfkill
  systemd:
      masked: yes
      name: "{{ item }}"
  with_items:
      - systemd-rfkill.service
      - systemd-rfkill.socket
