---
- name: add the current user to the docker group
  user:
    name: "{{ lookup('env', 'USER') }}"
    groups:
      - docker
    append: yes
  when: lookup('env', 'USER') != 'root'

# NB: it's almost never a good idea to install pip packages as root, which is what this does
# however it can't be helped in this case, as the docker_image module needs docker-py to be present
- name: install ansible's docker dependency
  pip:
    name: docker-py
