---
# yaourt is a pacman front-end https://wiki.archlinux.org/index.php/Yaourt
# NOTE: this front-end is no longer maintained and we need to migrate away from it.
# Should use 'yay' now.  Expect this task to be removed soon

# the 'aur' module has a simple internal implementation for building AUR packages
# such as 'yaourt' to bootstrap
- aur: name=yaourt use=makepkg skip_installed=true
  become: yes
  become_user: "{{ aur_builder_user }}"
