---
# yaourt is a pacman front-end https://wiki.archlinux.org/index.php/Yaourt
# the 'aur' module doesn't work right unless the base-devel package is installed
- name: Ensure base-devel is installed
  pacman:
      name: base-devel
      state: present

# Even base-devel isn't enough; also need package-query from AUR
- name: Ensure package-query is installed
  aur: name=package-query use=internal skip_installed=true
  become: yes
  become_user: "{{ aur_builder_user }}"

# the 'aur' module has a simple internal implementation for building AUR packages
# such as 'yaourt' to bootstrap
- aur: name=yaourt use=internal skip_installed=true
  become: yes
  become_user: "{{ aur_builder_user }}"

# 'yaourt' is now inactive as of 2018-04 so also install aurman and start to transition to that
# This transition will take some time and require changes, since yaourt operates on both AUR and the official 
# repositories, but aurman only operateson AUR, so pacman must be used to install official packages
- aur: name=aurman use=internal skip_installed=true
  become: yes
  become_user: "{{ aur_builder_user }}"
