---
- import_tasks: create-aur-builder-user.yml
- import_tasks: configure-pacman.yml
- import_tasks: install-yaourt.yml
- name: install base system packages that don't require X
  aur: 
    name: "{{ item }}"
    use: yaourt
    skip_installed: yes
  become: yes
  become_user: "{{ aur_builder_user }}"
  with_items:
      - "{{ utility_packages }}"
      - "{{ console_font_packages }}"
      - "{{ dev_packages }}"
      - "{{ laptop_packages }}"

- import_tasks: configure-tlp.yml
- import_tasks: configure-bluetooth.yml

