---
- name: install base system packages that don't require X
  dnf:
    name: "{{ item }}"
    state: present
  become: yes
  become_user: "{{ aur_builder_user }}"
  with_items:
      - "{{ utility_packages }}"
      - "{{ console_font_packages }}"
      - "{{ dev_packages }}"
      - "{{ pentest_packages }}"

- name: enable and start the smartcard service to support yubikeys
  systemd:
    name: pcscd.service
    enabled: yes
    state: started

- import_tasks: configure-tlp.yml
- import_tasks: configure-docker.yml
- import_tasks: configure-ufw-firewall.yml


