---
# This seems not to work without a password so it'll have to be
# a manual step for now
#- name: Use zsh as the login shell
  #user:
    #name: "{{ lookup('env', 'USER') }}"
    #shell: /bin/zsh

# These have been moved to my dotfiles repo, if I like that after a while these can be removed
#- file:
    #path: "{{ wallpapers_path }}"
    #state: directory

#- name: Copy the wallpapers I like
  #copy:
    #dest: "{{ wallpapers_path }}/"
    #src: files/wallpapers/

- name: Ensure rust programming language tools are installed
  shell: |
    curl https://sh.rustup.rs -sSf | sh -s -- --no-modify-path --default-toolchain stable -y
    source "{{ '~/.cargo/env' | expanduser }}"
    # install various rust components that are useful
    rustup component add rust-src rls-preview rust-analysis
  args:
    creates: "{{ '~/.cargo/env' | expanduser }}"
