---
# This seems not to work without a password so it'll have to be
# a manual step for now
#- name: Use zsh as the login shell
  #user:
    #name: "{{ lookup('env', 'USER') }}"
    #shell: /bin/zsh
- file:
    path: "{{ wallpapers_path }}"
    state: directory

- name: Copy the wallpapers I like
  copy:
    dest: "{{ wallpapers_path }}/"
    src: files/wallpapers/
