---
# This seems not to work without a password so it'll have to be
# a manual step for now
#- name: Use zsh as the login shell
  #user:
    #name: "{{ lookup('env', 'USER') }}"
    #shell: /bin/zsh

- name: Ensure rust programming language tools are installed
  shell: |
    curl https://sh.rustup.rs -sSf | sh -s -- --no-modify-path --default-toolchain stable -y
    source "~/.cargo/env"
    # install various rust components that are useful
    rustup install nightly
    rustup component add rust-src rls-preview rust-analysis
    # this last step might fail if rls is broken in nightly
    rustup component add --toolchain nightly rust-src rls-preview rust-analysis
  args:
    creates: "~/.cargo/env"
