---
# packages that apply specifically to laptops
laptop_packages:
    - wpa_supplicant
    - acpi
    - powertop
    - ethtool #for disable WoL
    - smartmontools
    - x86_energy_perf_policy # tlp uses this
    - tlp
    - systemd-boot-pacman-hook # make sure the systemd-boot binaries on /boot are in sync with the latest systemd
    - lm_sensors
    - cpupower # monitor and tweak CPU speed settings
    - thermald # monitor CPU temperature
    - mons # shell script for dealing with multiple monitors

